CREATE TABLE dbo.Orders ( 
	id                   bigint NOT NULL   IDENTITY,
	order_id             varchar(60)    ,
	email                varchar(60)    ,
	shipping_method      varchar(60)    ,
	quantity_total       varchar(50)    ,
	weight_total         varchar(50)    ,
	product_total        varchar(50)    ,
	shipping_total       varchar(50)    ,
	handling_total       varchar(50)    ,
	tax_total            varchar(50)    ,
	discount_total       varchar(50)    ,
	order_total          varchar(50)    ,
	cc_number_masked     varchar(60)    ,
	cc_exp               varchar(12)    ,
	processor_response   varchar(60)    ,
	payment_type         varchar(60)    ,
	payment_status       varchar(60)    ,
	processor_balance    varchar(60)    ,
	customer_id          varchar(50)    ,
	email_count          varchar(60)    ,
	ip_address           varchar(100)    ,
	tag_color            varchar(60)    ,
	source_name          varchar(100)    ,
	source_id            varchar(60)    ,
	fulfillment_name     varchar(100)    ,
	fulfillment_id       varchar(60)    ,
	tag_name             varchar(100)    ,
	folder_id            varchar(60)    ,
	date_added           varchar(60)    ,
	date_updated         varchar(60)    ,
	shipping_id          varchar(60)    ,
	CONSTRAINT Pk_Orders PRIMARY KEY ( id )
 );

CREATE TABLE dbo.Shipments ( 
	id                   bigint NOT NULL   IDENTITY,
	first_name           varchar(100)    ,
	last_name            varchar(100)    ,
	company              varchar(60)    ,
	address1             varchar(150)    ,
	address2             varchar(150)    ,
	address3             varchar(150)    ,
	address4             varchar(150)    ,
	city                 varchar(100)    ,
	sstate               varchar(100)    ,
	postal_code          varchar(20)    ,
	country              varchar(150)    ,
	phone                varchar(60)    ,
	CONSTRAINT Pk_Shipments PRIMARY KEY ( id )
 );

